services:
  - type: web
    name: wallet-analyzer
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: BASESCAN_API_KEY
        sync: false
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: RATE_LIMIT_MAX
        value: 50
